version: '3.8'
services:
  my_app:
    build:
      context: .
      dockerfile: single-stage.dockerfile
    expose:
      - '8080'
    deploy:
      replicas: 4
    restart: always
    environment:
      - PORT=8000
    networks:
      - front-network
  proxy:
    image: nginx:latest
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=8080
    depends_on:
      - my_app
    networks:
      - front-network
networks:
  front-network:
    driver: bridge